#!/usr/bin/env python3
"""Build the published **Executive summary** page (``docs/summary.html``).

This page exists because of a rule the whole project is built around: a missing
measurement is published as *not run, with the reason*, never as an estimate that
looks like a measurement. The page is the one place where every headline row -
measured or not - is visible together:

* the rows that carry numbers render from the files that produced them
  (``memory/live/forward-ladder.json``, ``data/real/official_price_eligibility.json``,
  ``data/real/prints/crosscheck.json``) and name those files;
* the rows that do not carry numbers render from ``research/EXEC_SUMMARY.json``,
  which is a register of blockers: what is missing, which lane owed it, and what
  would have to exist before the row may carry a number.

The page must never invent a value for a not-run row, and it must never quietly
drop one either: the list is written by hand in the register and rendered whole.
"""

from __future__ import annotations

import html
import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def ESC(value: object) -> str:
    return html.escape(str(value), quote=True)


def _load(path: str) -> dict:
    if not os.path.exists(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except (OSError, json.JSONDecodeError):
        return {}


def _money(value) -> str:
    if value in (None, ""):
        return "—"
    return f"${float(value):,.2f}"


def _badge(text: str, kind: str = "") -> str:
    cls = {"ok": "badge-ok", "warn": "badge-warn", "bad": "badge-bad"}.get(
        kind or _BADGE_KIND.get(str(text).upper(), ""), "badge-warn")
    return f'<span class="badge {cls}">{ESC(text)}</span>'


_BADGE_KIND = {
    "SETTLED": "ok", "MEASURED": "ok", "PASS": "ok", "AGREEMENT": "ok",
    "COLLECTED-OFFICIAL-CALENDAR": "ok", "FULL-OFFICIAL-SERIES": "ok",
    "PROVISIONAL-EXCHANGE-PRINTS": "warn", "WAITING-FOR-PRINTS": "warn",
    "NOTHING-SCHEDULED": "warn", "PENDING": "warn",
    "NOT RUN": "bad", "NOT-RUN": "bad", "INELIGIBLE": "bad",
}


def _nav() -> str:
    """The Season 1 nav, matched exactly.

    The executive summary is a Season 1 page, so it carries Season 1's nav; the
    section links it does not contain are reachable from the tables on the page
    and from the site root, which keeps every link on the page resolvable in a
    build that renders only this section.
    """
    links = [("index.html", "Overview"), ("desk/index.html", "Official Equities Desk"),
             ("summary.html", "Executive summary"),
             ("leaderboard.html", "Leaderboard"), ("strategies.html", "Strategies"),
             ("simulator.html", "Trade Simulator"), ("market.html", "Market &amp; factors"),
             ("sensitivity.html", "Venue sensitivity"),
             ("significance.html", "Significance"), ("methodology.html", "Methodology"),
             ("data.html", "Data provenance"), ("sources.html", "Sources"),
             ("irregularities.html", "Irregularities"), ("limitations.html", "Limitations"),
             ("participants/index.html", "Participants")]
    return "".join(
        f'<a class="{"active" if href == "summary.html" else ""}" href="{href}">{label}</a>'
        for href, label in links)


def page(title: str, body: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{ESC(title)} · StockPaperSim</title>
<meta name="description" content="Executive summary: every headline row either carries a
number from a named file or says NOT RUN with the reason and the artifact that would
unblock it.">
<link rel="stylesheet" href="assets/site.css">
</head>
<body>
<header class="site-header">
  <div class="wrap">
    <a class="brand" href="index.html">StockPaperSim</a>
    <span class="brand-sub">Executive summary · measured rows cite their file, unmeasured
    rows say why</span>
  </div>
  <nav class="wrap nav">{_nav()}</nav>
</header>
<main class="wrap">
<aside class="callout"><strong>Legacy research summary — not certified stock performance.</strong>
Daily prints and internally reproduced arithmetic do not establish observed intraday liquidity, pre-execution order submission, or T+1 cash settlement.
<a href="desk/index.html#trades">Open the strict equities audit</a> for every forward fill's exclusion reasons.</aside>
{body}
</main>
<footer class="site-footer">
  <div class="wrap">
    <p>Generated by <code>scripts/build_site_summary.py</code> from
    <code>research/EXEC_SUMMARY.json</code>, <code>memory/live/</code> and
    <code>data/real/</code>. CI rebuilds this page and diffs it, so a number on it
    cannot drift from the file it came from. Nothing here is investment advice.</p>
  </div>
</footer>
<script src="assets/site.js"></script>
</body>
</html>
"""


# --------------------------------------------------------------------------
# Sections
# --------------------------------------------------------------------------

def section_measured(ladder: dict, eligibility: dict, crosscheck: dict,
                     prints_manifest: dict) -> str:
    rows = ladder.get("ladder") or []
    body = ["<h2>What is measured</h2>",
            "<p>These rows are rendered from the files named beside them. Nothing "
            "else on this page carries a number.</p>"]

    # -- the rollover ladder ------------------------------------------------
    body.append("<h3>Forward rollover</h3>")
    if rows:
        body.append(
            "<p>The forward book steps itself through every session that has a "
            "published print. A session settles only when each trade it contains "
            "can cite a real published bar; the evidence column names the official "
            "series that have (<em>present</em>) and have not (<em>missing</em>) "
            "published that session's observation, so a provisional settlement is "
            "visible as provisional.</p>")
        body.append(f"<p><strong>Status:</strong> {_badge('MEASURED', 'ok')} "
                    f"{ESC(ladder.get('status', ''))}<br>"
                    f"<span class=\"note\">Plan date {ESC(ladder.get('plan_date',''))} · "
                    f"calendar authority {ESC(ladder.get('calendar_authority',''))} · "
                    f"executable prints {ESC(ladder.get('price_print_source',''))} "
                    f"({ESC(ladder.get('price_print_class',''))}, redistribution "
                    f"{ESC(ladder.get('price_print_class') and 'NOT-AUTHORIZED-FOR-REPOSITORY-REPRODUCTION' or '')}) "
                    f"· generated {ESC(ladder.get('generated_utc',''))} · source "
                    f"<code>memory/live/forward-ladder.json</code></span></p>")
        body.append("<table><thead><tr><th>Session</th><th>Verification</th>"
                    "<th class=\"num\">Intents</th><th class=\"num\">Filled</th>"
                    "<th class=\"num\">Waiting</th><th class=\"num\">Notional</th>"
                    "<th>Official series present</th><th>Official series missing</th>"
                    "</tr></thead><tbody>")
        for row in rows:
            present = ", ".join(p.get("sid", "") for p in row.get("official_series_present") or [])
            missing = ", ".join(row.get("official_series_missing") or [])
            body.append(
                f"<tr><td>{ESC(row.get('session'))}</td>"
                f"<td>{_badge(row.get('verification', ''))}</td>"
                f"<td class=\"num\">{ESC(row.get('intents_targeted'))}</td>"
                f"<td class=\"num\">{ESC(row.get('filled'))}</td>"
                f"<td class=\"num\">{ESC(row.get('waiting_for_prints'))}</td>"
                f"<td class=\"num\">{_money(row.get('notional_usd'))}</td>"
                f"<td>{ESC(present) or '—'}</td>"
                f"<td>{ESC(missing) or '—'}</td></tr>")
        body.append("</tbody></table>")
        fills = [f for row in rows for f in row.get("fills") or []]
        if fills:
            body.append("<details><summary>Every settled fill on the ladder "
                        f"({len(fills)})</summary><table><thead><tr><th>Intent</th>"
                        "<th>Participant</th><th>Symbol</th><th>Side</th>"
                        "<th class=\"num\">Qty</th><th class=\"num\">Price</th>"
                        "<th>Reference class</th></tr></thead><tbody>")
            for fill in fills:
                body.append(
                    f"<tr><td>{ESC(fill.get('intent_id'))}</td>"
                    f"<td>{ESC(fill.get('participant'))}</td>"
                    f"<td>{ESC(fill.get('symbol'))}</td>"
                    f"<td>{ESC(fill.get('side'))}</td>"
                    f"<td class=\"num\">{ESC(fill.get('quantity'))}</td>"
                    f"<td class=\"num\">{fill.get('price')}</td>"
                    f"<td>{ESC(fill.get('reference_source_class'))}</td></tr>")
            body.append("</tbody></table></details>")

        pending = ladder.get("pending_intents") or []
        if pending:
            body.append("<h4>Intents outstanding</h4><table><thead><tr>"
                        "<th>Participant</th><th>Symbol</th><th>Side</th>"
                        "<th class=\"num\">Qty</th><th>Target session</th>"
                        "<th>Status</th></tr></thead><tbody>")
            for intent in pending:
                body.append(
                    f"<tr><td>{ESC(intent.get('participant'))}</td>"
                    f"<td>{ESC(intent.get('symbol'))}</td>"
                    f"<td>{ESC(intent.get('side'))}</td>"
                    f"<td class=\"num\">{ESC(intent.get('quantity'))}</td>"
                    f"<td>{ESC(intent.get('intended_session'))}</td>"
                    f"<td>{_badge(intent.get('status', ''))}</td></tr>")
            body.append("</tbody></table>")
    else:
        body.append("<p>No rollover has run yet, so this row has no number. "
                    "Run <code>python3 -m sim.cli rollover</code> (or wait for the "
                    "scheduled workflow).</p>")

    # -- the print cross-check ---------------------------------------------
    body.append("<h3>Exchange-versus-vendor print cross-check</h3>")
    if crosscheck:
        verdict = crosscheck.get("verdict", "")
        body.append(
            f"<p>{_badge(verdict)} {ESC(verdict)}. Worst close difference "
            f"{crosscheck.get('worst_close_difference_bps')} bps over "
            f"{crosscheck.get('symbol_sessions_compared')} symbol-sessions, tolerance "
            f"{crosscheck.get('tolerance_bps')} bps. Source "
            f"<code>data/real/prints/crosscheck.json</code>.</p>")
    else:
        body.append("<p>No cross-check file has been built yet.</p>")

    # -- the strict gate ----------------------------------------------------
    body.append("<h3>Official-price eligibility (strict gate)</h3>")
    if eligibility:
        codes: dict = {}
        for value in (eligibility.get("symbols") or {}).values():
            for issue in value.get("issues") or []:
                codes[issue.get("code", "?")] = codes.get(issue.get("code", "?"), 0) + 1
        body.append(
            f"<p>{_badge('INELIGIBLE' if not eligibility.get('eligible') else 'ELIGIBLE')} "
            f"<code>eligible = {str(bool(eligibility.get('eligible'))).lower()}</code>. "
            f"Backend {ESC(eligibility.get('backend'))}, source class required "
            f"{ESC(eligibility.get('source_class_required'))}, redistribution statuses "
            f"accepted {ESC(', '.join(eligibility.get('redistribution_statuses_accepted') or []))}. "
            f"Window {ESC((eligibility.get('window') or {}).get('start'))} to "
            f"{ESC((eligibility.get('window') or {}).get('end'))}, "
            f"{ESC(eligibility.get('calendar_sessions_checked'))} sessions and "
            f"{len(eligibility.get('required_symbols') or [])} symbols checked. Source "
            f"<code>data/real/official_price_eligibility.json</code>.</p>")
        if codes:
            body.append("<ul>" + "".join(
                f"<li><code>{ESC(code)}</code> × {count}</li>"
                for code, count in sorted(codes.items())) + "</ul>")
            body.append("<p class=\"note\">Every code is a reason the gate is closed, "
                        "stated as the audit states it. Closing it is the point: an "
                        "official-price competition may only run on data this project "
                        "is allowed to republish, and that permission does not exist "
                        "yet.</p>")
    else:
        body.append("<p>No eligibility report has been built yet.</p>")

    # -- how the prints were obtained --------------------------------------
    if prints_manifest:
        body.append("<h3>How the forward prints were obtained</h3>")
        body.append("<p>The publisher rows in this build were transcribed from the "
                    "endpoints below in a session that had no outbound HTTPS, and "
                    "cross-checked against each other. Each row keeps the publisher's "
                    "own string and the URL it came from; the scheduled workflow "
                    "fetches the same endpoints directly so the next build does not "
                    "need the transcription step at all.</p>")
        body.append("<ul>" + "".join(
            f"<li><code>{ESC(row.get('id'))}</code>: {ESC(row.get('source_class'))} · "
            f"redistribution {ESC(row.get('redistribution_status'))} · "
            f"{ESC(row.get('url'))}</li>"
            for row in prints_manifest.get("sources") or []) + "</ul>")
    return "\n".join(body)


def section_intraday_check(payload: dict) -> str:
    """The check behind the three ``not_run`` rows, printed rather than asserted.

    Three of the rows below rest on one fact: no intraday capture has landed. A
    reader should not have to take that on trust, so the page carries the result
    of ``scripts/check_intraday_lane.py`` - the directory listing, the git history
    of the path, and the exact commands - beside the rows it supports.
    """
    if not payload:
        return ("<h3>Intraday capture check</h3><p>No check on file yet: run "
                "<code>python3 scripts/check_intraday_lane.py</code> to record one.</p>")
    tree = payload.get("tree") or {}
    rows = "".join(
        f"<tr><td><code>{ESC(rel)}</code></td>"
        f"<td>{'present' if state.get('exists') else 'absent'}</td>"
        f"<td>{state.get('files', 0)} file(s), {state.get('bytes', 0):,} bytes</td></tr>"
        for rel, state in sorted(tree.items()))
    return "\n".join([
        "<h3>Intraday capture check</h3>",
        f"<p><strong>{ESC(payload.get('verdict'))}</strong> in this working tree · "
        f"history: <code>{ESC(payload.get('history_check'))}</code> · checked "
        f"{ESC(payload.get('generated_utc'))} by "
        f"<code>scripts/check_intraday_lane.py</code>.</p>",
        "<table><thead><tr><th>Capture path</th><th>In this tree</th>"
        "<th>Contents</th></tr></thead><tbody>", rows, "</tbody></table>",
        f"<p>{ESC(payload.get('unblocks_when'))}</p>",
        "<p>The check answers two different questions and keeps them apart. The tree "
        "listing is definitive, which is the fact the rows below rest on. The history "
        "answer is weaker: this clone is shallow, so it reports "
        "<code>CANNOT_TELL_SHALLOW_CLONE</code> rather than claiming nothing was ever "
        "committed anywhere.</p>",
    ])


def section_not_run(register: dict) -> str:
    body = ["<h2>What is not run, and why</h2>",
            "<p>These rows are the ones this project has been asked for and cannot "
            "yet measure. Each one names the missing artifact and what would "
            "unblock it. A row stays here - with no number - until that artifact "
            "exists; it is never filled in from a proxy.</p>",
            "<table><thead><tr><th>Row</th><th>Status</th><th>Why there is no "
            "number</th><th>Missing artifact</th><th>Unblocks when</th>"
            "<th>Sources</th></tr></thead><tbody>"]
    for row in register.get("rows") or []:
        links = "".join(
            f'<a href="{ESC(link.get("url"))}">{ESC(link.get("label"))}</a><br>'
            for link in row.get("source_links") or [])
        body.append(
            f'<tr id="{ESC(row.get("id"))}"><td><strong>{ESC(row.get("label"))}</strong>'
            f'<br><code>{ESC(row.get("id"))}</code></td>'
            f'<td>{_badge("NOT RUN", "bad")}</td>'
            f'<td>{ESC(row.get("reason"))}</td>'
            f'<td><code>{ESC(row.get("missing_artifact"))}</code></td>'
            f'<td>{ESC(row.get("unblocks_when"))}</td>'
            f'<td>{links or "—"}</td></tr>')
    body.append("</tbody></table>")
    instructions = register.get("standing_instructions") or []
    if instructions:
        body.append("<h3>Standing rules this page obeys</h3><ul>" + "".join(
            f"<li>{ESC(item)}</li>" for item in instructions) + "</ul>")
    return "\n".join(body)


def build(memory_root: str, data_root: str, research_root: str, out: str) -> list:
    register = _load(os.path.join(research_root, "EXEC_SUMMARY.json"))
    ladder = _load(os.path.join(memory_root, "live", "forward-ladder.json"))
    eligibility = _load(os.path.join(data_root, "official_price_eligibility.json"))
    crosscheck = _load(os.path.join(data_root, "prints", "crosscheck.json"))
    prints_manifest = _load(os.path.join(data_root, "prints", "manifest.json"))
    intraday = _load(os.path.join(research_root, "INTRADAY_LANE_CHECK.json"))

    body = [
        "<h1>Executive summary</h1>",
        "<p>One page, every headline row. Rows that carry numbers name the file the "
        "numbers came from; rows that do not carry numbers say <strong>not run</strong> "
        "and why. The distinction is the whole point of this page: a forward test with "
        "an invented row in it is worth less than a shorter test without one.</p>",
        section_measured(ladder, eligibility, crosscheck, prints_manifest),
        section_not_run(register),
        section_intraday_check(_load(os.path.join(research_root,
                                                 "INTRADAY_LANE_CHECK.json"))),
    ]
    content = page("Executive summary", "\n".join(body))
    payload = {
        # No build clock: the payload has to be byte-identical across two builds
        # of the same inputs, and the ladder already carries the time of the run
        # that produced the numbers.
        "generated_utc": ladder.get("generated_utc", ""),
        "ladder": {"status": ladder.get("status"), "plan_date": ladder.get("plan_date"),
                   "sessions_settled": ladder.get("sessions_settled"),
                   "sessions_waiting": ladder.get("sessions_waiting"),
                   "ladder": ladder.get("ladder"),
                   "pending_intents": ladder.get("pending_intents")},
        "official_price_eligibility": {
            "eligible": eligibility.get("eligible"),
            "reason": eligibility.get("reason"),
            "backend": eligibility.get("backend"),
            "window": eligibility.get("window")},
        "print_crosscheck": crosscheck,
        "not_run": register.get("rows"),
        # The check behind the three not-run rows, so a reader of the payload
        # gets the same evidence as a reader of the page.
        "intraday_check": {
            "verdict": intraday.get("verdict"),
            "history_check": intraday.get("history_check"),
            "in_this_tree": intraday.get("in_this_tree"),
            "generated_utc": intraday.get("generated_utc"),
            "tree": intraday.get("tree")},
        "standing_instructions": register.get("standing_instructions"),
    }

    written = []
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "summary.html"), "w", encoding="utf-8") as handle:
        handle.write(content)
    written.append("summary.html")
    os.makedirs(os.path.join(out, "assets", "data"), exist_ok=True)
    with open(os.path.join(out, "assets", "data", "summary.json"), "w",
              encoding="utf-8") as handle:
        json.dump(payload, handle, indent=1, sort_keys=False, default=str)
        handle.write("\n")
    written.append("assets/data/summary.json")
    return written


def main(argv=None) -> int:
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--memory-root", default=os.path.join(REPO_ROOT, "memory"))
    parser.add_argument("--data-root", default=os.path.join(REPO_ROOT, "data", "real"))
    parser.add_argument("--research-root", default=os.path.join(REPO_ROOT, "research"))
    parser.add_argument("--out", default=os.path.join(REPO_ROOT, "docs"))
    args = parser.parse_args(argv)
    written = build(args.memory_root, args.data_root, args.research_root, args.out)
    print(f"summary site: {len(written)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
