#!/usr/bin/env python3
"""Generate the Season 2 site: collected prices, dated events, verified ledger.

Season 1's pages are built by ``scripts/build_site.py`` from the calibrated
replay. Season 2's pages are built here, from the Season 2 runs' memory plus the
collected files under ``data/real/``, because the questions a reader asks are
different: *which file did that price come from, and can I check it?*

Every page is generated from committed artefacts only - run memory, collected
data files and the register - so ``docs/`` can be diffed against a fresh build in
CI, and a page can never contain a number that is not also in a machine-readable
artefact next to it.
"""

from __future__ import annotations

import gzip
import html
import json
import os
import sys
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from build_site import (ESC, F0, F2, F3, F4, F5, FC0SP, FC2, FD0, NA,  # noqa: E402
                        badge, bar_chart, card, hbar_chart, line_chart, money,
                        num, signed, status_badge, table)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)
from sim import eligibility as price_eligibility  # noqa: E402
from sim import realdata  # noqa: E402


PRICE_STATUS_BANNER = (
    '<section class="card notice"><h2>Official-price eligibility is checked, not assumed</h2>'
    '<p>The page builder has not yet loaded a run-specific eligibility report. '
    'Use <code>python3 -m sim.cli price-audit</code> before treating any result as an '
    'official-price competition.</p></section>')

#: Navigation targets are written as site-root-relative paths, and every link is
#: prefixed with the depth of the page being rendered. Writing them relative to
#: the Season 2 directory instead produced links that resolved one level too high
#: (docs/season2/*.html pointing at docs/season2/season2/*.html), which the
#: published-site test caught.
NAV = [
    ("season2/index.html", "Overview"),
    ("season2/leaderboard.html", "Leaderboard"),
    ("season2/masterfeed.html", "MasterFeed"),
    ("season2/ledger.html", "Trade ledger"),
    ("season2/stress.html", "Stress panel"),
    ("season2/data.html", "Data custody"),
    ("season2/participants/index.html", "Participants"),
    ("summary.html", "Executive summary"),
    ("simulator.html", "Live Simulator"),
    ("live/index.html", "Live Book"),
    ("index.html", "Season 1"),
]


def page(title: str, body: str, active: str = "", depth: int = 1) -> str:
    pre = "../" * depth
    nav = "".join(
        f'<a class="{"active" if href == active else ""}" href="{pre}{href}">{label}</a>'
        for href, label in NAV)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{ESC(title)} · StockPaperSim Season 2</title>
<meta name="description" content="StockPaperSim Season 2: fourteen strategies derived
from the MasterSite project directory, with eligibility-gated collected prices, dated
events, and a trade ledger that can be re-derived from the raw files.">
<link rel="stylesheet" href="{pre}assets/site.css">
</head>
<body>
<header class="site-header">
  <div class="wrap">
    <a class="brand" href="{pre}index.html">StockPaperSim</a>
    <span class="brand-sub">Season 2 · MasterFeed Invitational · eligibility-gated prices</span>
  </div>
  <nav class="wrap nav">{nav}</nav>
</header>
<main class="wrap">
{PRICE_STATUS_BANNER}
{body}
</main>
<footer class="site-footer">
  <div class="wrap">
    <p>Season 2 displays <strong>collected daily bars</strong> and dated events, but
    a public response is not automatically an eligible official price source. The
    current historical research run uses Yahoo Finance files marked
    <strong>SECONDARY</strong>; the official Nasdaq adapter preserves raw responses,
    checksums and licensing status and fails closed when those checks are not met.
    Real share volume is used for participation and liquidity modelling. What remains
    modelled is named on every page and registered in the irregularity register.
    Nothing here is investment advice.</p>
    <p>Generated by <code>scripts/build_site_season2.py</code> from
    <code>memory/runs/season2-*</code> and <code>data/real/</code>; CI diffs a fresh
    rebuild against this directory.</p>
  </div>
</footer>
<script src="{pre}assets/site.js"></script>
</body>
</html>
"""


LEVEL_BADGE = {"OFFICIAL": "badge-ok", "OFFICIAL-VENDOR": "badge-ok",
               "SECONDARY": "badge-warn", "ASSERTED": "badge-bad",
               "UNPROVEN-MAPPING": "badge-bad", "WEAK-MAPPING": "badge-warn",
               "STRONG-MAPPING": "badge-ok", "FORWARD-ONLY": "badge-warn",
               "BACKTESTED": "badge-ok", "DATA-MISSING": "badge-bad",
               "NOT-RETRIEVABLE": "badge-bad", "AVAILABLE": "badge-ok",
               "MISSING": "badge-bad"}


def pill(text: str, kind: Optional[str] = None) -> str:
    return f'<span class="badge {kind or LEVEL_BADGE.get(text, "")}">{ESC(text)}</span>'


# --------------------------------------------------------------------------
# data loading
# --------------------------------------------------------------------------

def _read_json(path: str, default=None):
    if not os.path.exists(path):
        return default
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _read_jsonl(path: str) -> List[dict]:
    if os.path.exists(path + ".gz"):
        with gzip.open(path + ".gz", "rt", encoding="utf-8") as handle:
            return [json.loads(line) for line in handle if line.strip()]
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as handle:
            return [json.loads(line) for line in handle if line.strip()]
    return []


class Season2Site:
    """All Season 2 artefacts the pages need, loaded once."""

    def __init__(self, root: str, run_id: str = "") -> None:
        self.root = root
        runs_dir = os.path.join(root, "runs")
        runs = sorted((d for d in os.listdir(runs_dir) if d.startswith("season2-")),
                      ) if os.path.isdir(runs_dir) else []
        if not runs:
            raise SystemExit(f"no season2-* runs under {runs_dir}")
        primary = [r for r in runs if "-primary-" in r] or runs
        self.run_id = run_id or primary[-1]
        self.dir = os.path.join(runs_dir, self.run_id)
        self.manifest = _read_json(os.path.join(self.dir, "manifest.json")) or {}
        self.leaderboard = (_read_json(os.path.join(self.dir, "leaderboard.json"))
                            or {}).get("leaderboard", [])
        self.market = _read_json(os.path.join(self.dir, "market_report.json")) or {}
        self.participants = _read_json(os.path.join(self.dir, "participants.json")) or []
        self.masterfeed = _read_json(os.path.join(self.dir, "masterfeed.json")) or {}
        self.signals = _read_json(os.path.join(self.dir, "signal_book.json")) or {}
        self.verification = _read_json(os.path.join(self.dir, "verification.json")) or {}
        self.market_data = _read_json(os.path.join(self.dir, "market_data.json")) or {}
        self.reports: Dict[str, dict] = {}
        reports_dir = os.path.join(self.dir, "reports")
        if os.path.isdir(reports_dir):
            for name in sorted(os.listdir(reports_dir)):
                if name.endswith(".json"):
                    rep = _read_json(os.path.join(reports_dir, name))
                    if rep and rep.get("username"):
                        self.reports[rep["username"]] = rep
        self.trips = _read_jsonl(os.path.join(self.dir, "ledger_trips.jsonl"))
        self.fills = _read_jsonl(os.path.join(self.dir, "ledger_fills.jsonl"))
        self.curves: Dict[str, List[Tuple[str, float]]] = {}
        for row in _read_jsonl(os.path.join(self.dir, "events", "equity.jsonl")):
            self.curves.setdefault(row["participant"], []).append(
                (row["date"], row["equity"]))
        self.stress: List[dict] = []
        for other in runs:
            if other == self.run_id:
                continue
            self.stress.append({
                "run_id": other,
                "label": (_read_json(os.path.join(runs_dir, other, "manifest.json"))
                          or {}).get("label", other),
                "leaderboard": (_read_json(os.path.join(runs_dir, other,
                                                        "leaderboard.json"))
                                or {}).get("leaderboard", [])})
        self.stress.sort(key=lambda s: s["label"])
        self.collection = _read_json(os.path.join(REPO_ROOT, "data", "real",
                                                  "collection_manifest.json")) or {}
        self.coverage = _read_json(os.path.join(REPO_ROOT, "data", "real",
                                                "coverage_report.json")) or {}
        self.crosscheck = _read_json(os.path.join(REPO_ROOT, "data", "real",
                                                  "crosschecks",
                                                  "price_crosscheck.json")) or {}
        self.provenance = _read_json(os.path.join(self.dir, "data_provenance.json")) or {}
        diagnostics = self.provenance.get("diagnostics") or {}
        self.price_backend = (self.provenance.get("price_source") or
                              diagnostics.get("price_backend") or "yahoo")
        self.price_classes = sorted({str(meta.get("source_class", "UNKNOWN"))
                                     for meta in (diagnostics.get("price_series") or {}).values()})
        self.price_eligibility = price_eligibility.audit_official_prices(
            root=os.path.join(REPO_ROOT, "data", "real"), symbols=realdata.UNIVERSE,
            start=realdata.SEASON2_WARMUP_START, end=realdata.SEASON2_END,
            backend=price_eligibility.OFFICIAL_PRICE_BACKEND)

    # -- lookups -----------------------------------------------------------
    def spec(self, username: str) -> dict:
        return next((p for p in self.participants if p.get("username") == username), {})

    def verification_for(self, username: str) -> dict:
        return next((v for v in self.verification.get("per_participant", [])
                     if v.get("username") == username), {})

    def trips_for(self, username: str) -> List[dict]:
        return [t for t in self.trips if t.get("participant") == username]

    def fills_for(self, username: str) -> List[dict]:
        return [f for f in self.fills if f.get("participant") == username]

    def curve(self, username: str) -> List[Tuple[str, float]]:
        return self.curves.get(username, [])

    def benchmark(self) -> List[Tuple[str, float]]:
        dates = self.market_data.get("dates") or []
        spx = self.market_data.get("spx") or []
        t0 = self.market_data.get("first_competition_index") or 0
        start = (self.manifest.get("competition") or {}).get("starting_cash", 100_000.0)
        if not dates or t0 <= 0 or t0 >= len(spx):
            return []
        base = spx[t0 - 1]
        return [(dates[t], start * spx[t] / base) for t in range(t0, len(spx))]

    def signal_status(self) -> Dict[str, str]:
        return {k: v.get("state") for k, v in (self.masterfeed.get("availability")
                                               or {}).items()}

    def inventory(self) -> dict:
        prov = _read_json(os.path.join(self.dir, "data_provenance.json")) or {}
        return prov.get("inventory") or {}


def _slug(username: str) -> str:
    return username.lstrip("@").replace("/", "_")


def _grid(charts: Sequence[str]) -> str:
    return '<section class="charts">' + "".join(charts) + "</section>"


def _kpis(rows: Sequence[Tuple[str, str, str]]) -> str:
    return '<section class="kpis">' + "".join(
        f'<div class="kpi"><div class="kpi-label">{ESC(k)}</div>'
        f'<div class="kpi-value">{v}</div><div class="kpi-sub">{ESC(s)}</div></div>'
        for k, v, s in rows) + "</section>"


def _link(url: str, text: Optional[str] = None, keep: int = 78) -> str:
    if not url:
        return NA
    shown = text or (url if len(url) <= keep else url[:keep] + "…")
    return f'<a href="{ESC(url)}">{ESC(shown)}</a>'


# --------------------------------------------------------------------------
# pages
# --------------------------------------------------------------------------

def build_index(d: Season2Site) -> str:
    board, man, market = d.leaderboard, d.manifest, d.market
    summary = d.verification.get("summary") or {}
    winner = board[0] if board else {}
    bench = d.benchmark()
    winner_curve = d.curve(winner.get("username", ""))
    charts = []
    if winner_curve:
        charts.append(line_chart([(winner["username"], winner_curve),
                                  ("S&P 500 scaled", bench)],
                                 title="Winner against the real S&P 500",
                                 y_format=FD0))
    if board:
        charts.append(bar_chart([(r["username"], r["total_return_pct"]) for r in board],
                                height=280, y_format=FC0SP,
                                title="Total return by participant (%)"))
    signals = d.signal_status()
    available = sorted(k for k, v in signals.items() if v == "AVAILABLE")
    missing = sorted(k for k, v in signals.items() if v != "AVAILABLE")
    run_eligible = (d.price_eligibility.get("eligible") and
                    d.price_backend == "nasdaq" and d.price_classes == ["OFFICIAL"])
    if run_eligible:
        price_sentence = "The run passed the official-price eligibility gate."
    else:
        price_sentence = (f"The committed artifact uses {d.price_backend} price files "
                          f"classed {', '.join(d.price_classes) or 'UNKNOWN'} and is "
                          "reproducible research, not an official-price-eligible result.")
    body = f"""
<h1>Season 2 &mdash; the MasterFeed Invitational</h1>
<p class="lede">Fourteen strategies derived from the
<a href="https://buffedlizard55-lab.github.io/MasterSite/">MasterSite</a> project
directory, each with its own username and $100,000 of paper capital.
{price_sentence}
({man.get('competition', {}).get('start')} &rarr; {man.get('competition', {}).get('end')},
{market.get('window', {}).get('sessions', 0)} sessions). Every fill is written to a
ledger that carries the session's collected open, high, low, close and volume, the file
and SHA-256 those came from, the participation rate against the collected volume, and the
full cost breakdown. An official run must pass the banner audit first. The intraday
path inside each daily bar is still modelled; that, and everything else modelled, is
named in the <a href="data.html">data custody</a> page and the
<a href="../irregularities.html">irregularity register</a>.</p>
{_kpis([
    ("Participants", str(len(board)), "one strategy, one username"),
    ("Winner", winner.get("username", "—"), f"{winner.get('total_return_pct', 0):+.2f}%"),
    ("S&P 500 over the window", f"{market.get('spx_return_pct', 0):+.2f}%",
     "real FRED SP500 closes"),
    ("Fills in the ledger", f"{summary.get('fill_count', 0):,}",
     f"{summary.get('order_days', 0):,} sessions with a fill"),
    ("Round trips closed", f"{summary.get('round_trips_closed', 0):,}",
     f"{summary.get('round_trips_open', 0)} open at the season end"),
    ("Mean slippage vs the collected open", f"{summary.get('slippage_vs_open_bps_mean', 0)} bps",
     "fill price against the collected session open"),
    ("Largest participation", f"{summary.get('max_participation_pct', 0)} %",
     "share of the collected session volume, capped by the venue"),
    ("Ledger digest", f"<code>{ESC(str(d.verification.get('ledger_digest_sha256', ''))[:16])}…</code>",
     "SHA-256 over every ledger file"),
])}
{_grid(charts)}
{card("Read this first", '''
<p>Three things separate this season from a typical backtest:</p>
<ol>
<li><strong>The collected bars are individually traceable.</strong> Each participant
page lists fills next to the collected close for that session and the data file the
price came from. <code>scripts/independent_audit_season2.py</code> re-derives every
published number from those files without importing the simulation; the eligibility
banner says whether the source is approved for an official competition.</li>
<li><strong>A missing signal is reported, not filled in.</strong> Where a source
could not be retrieved as history (injury feeds, pre-game model predictions), the
strategy is registered as forward-only and places no backdated trades.</li>
<li><strong>The venue is stress-tested, not assumed.</strong> The same collected price
path is re-traded with doubled costs and with thinner displayed liquidity, and every
participant's return is published under all three assumptions; the eligibility status
above applies to all of them.</li>
</ol>''', cls="notice")}
{card("Simulating real trades &amp; upcoming order placement", '''
<p class="lede">Can strategies place upcoming trades and simulate a real trading experience?
<strong>Yes.</strong> Strategies and manual operators can stage upcoming orders for the next
trading session open (09:30 ET) or close (16:00 ET) across Nasdaq, NYSE, and S&amp;P 500 equities.
The simulator calculates live Level 2 depth queues, Almgren-Chriss market impact, Reg NMS Rule 612 tick increments,
statutory SEC &sect;31 and FINRA TAF fees, and tracks positions on a verified SHA-256 trade ledger.</p>
<p class="more"><a href="../simulator.html">Launch Interactive US Equities Trade Simulator &amp; Order Engine &rarr;</a></p>
''')}
{card("What the signals were, and whether the data existed", f'''
<p>{len(available)} collected signal families are available and {len(missing)} are
not. Available: {', '.join(f'<code>{ESC(s)}</code>' for s in available)}.</p>
<p>Missing, with the reason recorded in the signal book:
{', '.join(f'<code>{ESC(s)}</code>' for s in missing) or 'none'}.</p>
<p><a href="masterfeed.html">The MasterFeed register &rarr;</a> lists, per MasterSite
project, the official endpoint a strategy reads, how strong the mapping to a tradable
instrument is, and whether the history could be collected at all.</p>''')}
"""
    return page("Overview", body, active="season2/index.html")


def build_leaderboard(d: Season2Site) -> str:
    rows = []
    for r in d.leaderboard:
        rep = d.reports.get(r["username"], {})
        ver = d.verification_for(r["username"])
        trades = rep.get("trades") or {}
        rows.append([
            str(r["rank"]),
            f'<a href="participants/{_slug(r["username"])}.html">{ESC(r["username"])}</a>',
            ESC(str(r.get("archetype", ""))),
            signed(r["total_return_pct"]), money(r.get("final_equity")),
            signed(r.get("max_drawdown_pct")),
            num(r.get("sharpe"), F2), num(r.get("beta"), F2),
            num(rep.get("sessions_with_orders"), F0),
            num(trades.get("closed"), F0),
            num(ver.get("derived_realized_pnl_usd"), FC2),
            num(ver.get("equity_residual_usd"), F4),
            num(ver.get("rounding_bound_usd"), F2),
        ])
    signal_rows = []
    for username, meta in sorted(d.signal_status().items()):
        fire = (d.masterfeed.get("fire_counts") or {}).get(username, {})
        signal_rows.append([f"<code>{ESC(username)}</code>", pill(meta),
                            str(fire.get("sessions_actionable", "—")),
                            str(fire.get("sessions_in_window", "—")),
                            num(fire.get("last_value"), F4),
                            _link((d.masterfeed.get("availability") or {}).get(
                                username, {}).get("url", ""))])
    body = f"""
<h1>Season 2 leaderboard</h1>
<p class="lede">Ranked on total return, the metric the referenced competitions use.
The eligibility banner above controls whether this is an official-price result or a
clearly labelled secondary-source research replay. "Realised P&amp;L (ledger)" is
re-derived from the raw fill stream by
<code>sim/ledger.py</code> rather than read from the engine's own total; the residual
column is the difference between the engine's final equity and the equity re-derived
from those fills plus reported carry, and it is compared against the rounding bound
the 6-decimal stored prices can produce. Anything larger is a bug, and the build
fails rather than publishing it.</p>
{table(["#", "username", "archetype", "total return %", "final equity", "max DD %",
        "Sharpe", "beta", "sessions with orders", "closed trades",
        "realised P&L (ledger) $", "equity residual $", "rounding bound $"], rows)}
<p class="muted small">Real S&amp;P 500 over the same sessions:
{d.market.get('spx_return_pct', 0):+.2f}% (FRED SP500). A participant with no rows of
trades is one whose signal had no collected history: the season still records it, at
0.00%, and says why on its own page.</p>
{card("Signal provenance behind every number", table(
    ["signal", "collected state", "sessions actionable", "sessions in window",
     "value on the last session", "official source"], signal_rows))}
"""
    return page("Leaderboard", body, active="season2/leaderboard.html")


def build_masterfeed(d: Season2Site) -> str:
    register = d.masterfeed.get("register") or []
    availability = d.masterfeed.get("availability") or {}
    fire = d.masterfeed.get("fire_counts") or {}
    rows = []
    for row in register:
        signals = row.get("signals") or []
        states = sorted({availability.get(s, {}).get("state", "MISSING")
                         for s in signals}) if signals else []
        if not signals:
            collected = pill("NO-COLLECTED-SIGNAL", "badge-warn")
        elif states == ["AVAILABLE"]:
            collected = pill("AVAILABLE", "badge-ok")
        elif "AVAILABLE" in states:
            collected = pill("PARTIAL", "badge-warn")
        else:
            collected = pill("MISSING", "badge-bad")
        fired = "—"
        if signals:
            counts = [fire.get(s, {}) for s in signals]
            fired = ", ".join(
                f"{s.split('::')[0]}: {c.get('sessions_actionable', '—')}"
                for s, c in zip(signals, counts))
        rows.append([
            ESC(str(row.get("requested_as", ""))),
            _link(str(row.get("site_url", "")), row.get("repo") or "no such project"),
            _link(str(row.get("official_url", ""))),
            pill(str(row.get("source_class", ""))),
            pill(str(row.get("mapping", ""))),
            pill(str(row.get("status", ""))),
            collected,
            f'<code>{ESC(", ".join(signals))}</code>' if signals else NA,
            ESC(str(row.get("mapping_note", ""))),
        ])
    forward = [r for r in register if r.get("status") == "FORWARD-ONLY"]
    body = f"""
<h1>MasterFeed &mdash; what could be verified, and what could not</h1>
<p class="lede">Each row is one item from the brief, traced to the project it names and
to the <strong>official endpoint</strong> a strategy reads. "source class" says who
publishes the data, "mapping" says how strong the link from that project's data to a
tradable instrument honestly is, "status" says whether a backtest was possible at all,
and "collected data" says whether the season actually holds the signal. Nothing is
marked available because it would be convenient.</p>
{table(["requested as", "project", "official source", "source class", "mapping",
        "status", "collected data", "signal arrays", "why this mapping"], rows)}
{card("Forward-only: the strategies that place no backdated trades", f'''
<p>{len(forward)} of {len(register)} items have no retrievable official history:
<ul>{"".join(f"<li><strong>{ESC(str(r.get('requested_as')))}</strong> &mdash; {ESC(str(r.get('mapping_note', '')))}</li>" for r in forward)}</ul></p>
<p>Those strategies exist in the roster, their adapters point at the live official
document, and they report <em>no trades</em> for the season rather than a number built
from data this project could not verify. A scheduled collection run is what turns them
into backtestable participants, and that is the first item in the remaining-work
register.</p>''', cls="notice")}
{card("Signal arrays the season actually holds", table(
    ["signal", "collected state", "sessions actionable", "sessions in window",
     "value on the last session", "official source"],
    [[f"<code>{ESC(k)}</code>", pill(v.get("state", "")),
      str((fire.get(k) or {}).get("sessions_actionable", "—")),
      str((fire.get(k) or {}).get("sessions_in_window", "—")),
      num((fire.get(k) or {}).get("last_value"), F4),
      _link(availability.get(k, {}).get("url", ""))]
     for k, v in sorted(availability.items())]))}
{card("Where the money actually came from", '''
<p>The register answers "could it be measured"; the participant pages answer "did it
make money, and why". Each carries the strategy as declared before the run, its
returns, a post-mortem built from measured quantities only - never from the strategy's
own priors - its round trips with the collected reference prices, and its verification
block.</p>
<p><a href="participants/index.html">All participants &rarr;</a> &middot;
<a href="ledger.html">Trade ledger &rarr;</a></p>''')}
"""
    return page("MasterFeed register", body, active="season2/masterfeed.html")


def build_ledger(d: Season2Site) -> str:
    summary = d.verification.get("summary") or {}
    per_user = []
    for r in d.leaderboard:
        user = r["username"]
        fills = d.fills_for(user)
        trips = [t for t in d.trips_for(user) if t.get("status") == "closed"]
        if not fills:
            per_user.append([ESC(user), "0", "0", money(0.0), NA, NA, NA])
            continue
        parts = [f.get("participation_pct_of_session_volume") for f in fills
                 if f.get("participation_pct_of_session_volume") is not None]
        slip_open = [f.get("slippage_vs_open_bps") for f in fills
                     if f.get("slippage_vs_open_bps") is not None]
        slip_close = [f.get("slippage_vs_close_bps") for f in fills
                      if f.get("slippage_vs_close_bps") is not None]
        per_user.append([
            f'<a href="participants/{_slug(user)}.html">{ESC(user)}</a>',
            str(len(fills)), str(len(trips)),
            money(sum(t.get("net_pnl_usd", 0.0) for t in trips)),
            num(_mean(parts), F5), num(_mean(slip_open), F2), num(_mean(slip_close), F2)])
    biggest = sorted([t for t in d.trips if t.get("status") == "closed"],
                     key=lambda t: -abs(t.get("net_pnl_usd", 0.0)))[:60]
    trip_rows = [[ESC(str(t.get("participant", ""))), ESC(str(t.get("symbol", ""))),
                  ESC(str(t.get("direction", ""))), ESC(str(t.get("entry_date", ""))),
                  f'{t.get("entry_price", 0):.2f}', ESC(str(t.get("exit_date", ""))),
                  f'{t.get("exit_price", 0):.2f}', str(t.get("quantity", 0)),
                  money(t.get("gross_pnl_usd")), money(t.get("fees_usd")),
                  money(t.get("net_pnl_usd")), str(t.get("entry_fill_count", "")),
                  ESC(str(t.get("exit_reason") or t.get("entry_reason") or "")[:70])]
                 for t in biggest]
    fills_rows = [[ESC(str(f.get("date"))), ESC(str(f.get("symbol"))),
                   ESC(str(f.get("side"))), str(f.get("filled_qty")),
                   f'{f.get("avg_price", 0):.4f}',
                   num(f.get("reference_open"), FC2), num(f.get("reference_high"), FC2),
                   num(f.get("reference_low"), FC2), num(f.get("reference_close"), FC2),
                   num(f.get("reference_volume"), F0),
                   num(f.get("participation_pct_of_session_volume"), F5),
                   num(f.get("slippage_vs_open_bps"), F2),
                   num(f.get("slippage_vs_close_bps"), F2),
                   num(f.get("total_cost"), F4),
                   f'<code>{ESC(str(f.get("reference_file", "")))}</code>']
                  for f in sorted(d.fills, key=lambda f: (f.get("date", ""),
                                                          f.get("symbol", "")))[:400]]
    body = f"""
<h1>Trade ledger</h1>
<p class="lede">Every execution in Season 2, with the collected bar it filled against.
A round trip is derived per fill with average-cost accounting: a same-side fill blends
into the lot, an opposite-side fill closes it at the lot's average cost, and a fill
that crosses zero closes the lot and opens a new one. The ledger is written as
JSONL + CSV beside the run memory and hashed; the CSV is the file to load if you want
to re-analyse the season yourself.</p>
{_kpis([
    ("Fills", f"{summary.get('fill_count', 0):,}",
     f"across {summary.get('order_days', 0):,} sessions"),
    ("Notional traded", money(summary.get("total_notional_usd")),
     "sum of |filled quantity x price|"),
    ("Round trips closed", f"{summary.get('round_trips_closed', 0):,}",
     f"{summary.get('round_trips_open', 0)} open at the end"),
    ("Gross P&L from round trips", money(summary.get("gross_pnl_usd")),
     "before explicit cash costs"),
    ("Net P&L from round trips", money(summary.get("net_pnl_usd")),
     "after commission, exchange and regulatory fees"),
    ("Win rate", f"{summary.get('win_rate_pct', 0)}%", "closed round trips"),
    ("Mean holding period", f"{summary.get('average_holding_sessions', 0)} sessions",
     "entry to exit"),
    ("Modelled execution cost", money(summary.get("total_modelled_execution_cost_usd")),
     "spread + depth + impact inside the fill prices"),
])}
{card("By participant", table(
    ["participant", "fills", "closed round trips", "net P&L $",
     "mean participation % of collected volume", "mean slippage vs collected open (bps)",
     "mean slippage vs collected close (bps)"], per_user))}
{card("Largest 60 round trips", table(
    ["participant", "symbol", "direction", "entry date", "entry px", "exit date",
     "exit px", "qty", "gross $", "fees $", "net $", "tranches", "reason"], trip_rows))}
{card("First 400 fills against the collected bar", table(
    ["date", "symbol", "side", "qty", "fill px", "collected open", "collected high", "collected low",
     "collected close", "collected volume", "participation %", "slip vs open (bps)",
     "slip vs close (bps)", "modelled cost $", "price file"], fills_rows))}
<p class="muted small">Full ledger files:
<code>memory/runs/{ESC(d.run_id)}/ledger_fills.jsonl</code>,
<code>ledger_trips.jsonl</code>, <code>ledger_fills.csv</code>, with SHA-256 hashes in
<code>ledger_manifest.json</code> and per-participant re-derivations in
<code>verification.json</code>.</p>
"""
    return page("Trade ledger", body, active="season2/ledger.html")


def build_stress(d: Season2Site) -> str:
    labels = ["primary"] + [s["label"] for s in d.stress]
    names = [r["username"] for r in d.leaderboard]
    cells: Dict[str, Dict[str, float]] = {"primary": {
        r["username"]: r["total_return_pct"] for r in d.leaderboard}}
    for s in d.stress:
        cells[s["label"]] = {r["username"]: r["total_return_pct"]
                             for r in s["leaderboard"]}
    rows = [[f"<code>{ESC(n)}</code>"] + [
        signed(cells.get(label, {}).get(n)) for label in labels] for n in names]
    order = [[] for _ in labels]
    for n in names:
        for i, label in enumerate(labels):
            order[i].append((n, cells.get(label, {}).get(n)))
    rank_rows = []
    for i, label in enumerate(labels):
        ranked = sorted([(n, v) for n, v in order[i] if v is not None],
                        key=lambda x: -x[1])
        rank_rows.append([ESC(label)] + [
            f"{j + 1}. {ESC(n)} ({v:+.1f}%)" for j, (n, v) in enumerate(ranked[:5])])
    deltas = []
    for n in names:
        base = cells.get("primary", {}).get(n)
        if base is None:
            continue
        for label in labels[1:]:
            v = cells.get(label, {}).get(n)
            if v is None:
                continue
            deltas.append((abs(v - base), label, n, base, v))
    deltas.sort(reverse=True)
    delta_rows = [[ESC(n), ESC(label), signed(base), signed(v), signed(v - base)]
                  for _, label, n, base, v in deltas[:15]]
    body = f"""
<h1>Stress panel &mdash; the same collected path, a harder venue</h1>
<p class="lede">The collected price path is one realisation: there is no synthetic-seed
panel to average over the way Season 1 has one. What is still a modelling choice is
the venue, so Season 2 re-trades the identical collected bars under two harder
assumptions and publishes every participant's return under all three. A strategy
whose edge survives both is not relying on a cheap spread.</p>
{card("Assumptions", '''
<ul>
<li><strong>primary</strong> &mdash; the venue as declared in <code>sim/config.py</code>:
the tick-constrained spread model, the square-root impact model, a 10% participation
cap of the collected session volume, and a zero-commission retail broker that still pays
exchange and regulatory fees.</li>
<li><strong>stress-costs2x</strong> &mdash; spread coefficient doubled, impact
coefficient doubled, taker fee per share doubled, and a $1.00 commission per order
(the price the referenced paper competitions charge).</li>
<li><strong>stress-thinliquidity</strong> &mdash; displayed depth at the touch halved
and the participation cap cut from 10% to 5% of the collected session volume.</li>
</ul>''', cls="notice")}
{card("Total return under each assumption (%)", table(["participant"] + [
    ESC(l) for l in labels], rows))}
{card("Ranking is not stable under venue assumptions", table(
    ["assumption"] + [f"top {i + 1}" for i in range(5)], rank_rows))}
{card("Largest changes against the primary assumption", table(
    ["participant", "assumption", "primary %", "stressed %", "change"], delta_rows))}
"""
    return page("Stress panel", body, active="season2/stress.html")


def build_data(d: Season2Site) -> str:
    prov = _read_json(os.path.join(d.dir, "data_provenance.json")) or {}
    diag = prov.get("diagnostics") or {}
    cross = (prov.get("crosschecks") or {})
    inventory = prov.get("inventory") or {}
    price_rows = []
    for symbol, meta in sorted((diag.get("price_series") or {}).items()):
        price_rows.append([
            ESC(symbol), ESC(str(meta.get("provider", ""))),
            pill(str(meta.get("source_class", ""))),
            f'{meta.get("first_bar")} → {meta.get("last_bar")}',
            str(meta.get("bars_in_window", "")),
            str(meta.get("sessions_forward_filled", "")),
            str(meta.get("dividends_in_window", "")),
            num(meta.get("beta_vs_fred_spx"), F3),
            num(meta.get("sigma_idio_annual_estimated"), F3),
            f'<code>{ESC(str(meta.get("sha256", ""))[:16])}…</code>',
            f'<code>{ESC(str(meta.get("file", "")))}</code>',
        ])
    requests = d.collection.get("requests") or []
    ok = [r for r in requests if r.get("ok")]
    failed = [r for r in requests if not r.get("ok")]
    req_rows = [[ESC(str(r.get("kind", ""))), pill("OK" if r.get("ok") else "FAILED",
                                                   "badge-ok" if r.get("ok") else "badge-bad"),
                 str(r.get("status", "")), f'{r.get("bytes", 0):,}',
                 _link(str(r.get("url", ""))), ESC(str(r.get("error") or "")[:60])]
                for r in requests[:150]]
    inv_rows = [[f'<code>{ESC(str(f.get("path", "")))}</code>', f'{f.get("bytes", 0):,}',
                 f'<code>{ESC(str(f.get("sha256", ""))[:16])}…</code>']
                for f in (inventory.get("files") or [])]
    run_eligible = (d.price_eligibility.get("eligible") and
                    d.price_backend == "nasdaq" and d.price_classes == ["OFFICIAL"])
    audit_state = "PASS" if run_eligible else "NOT ELIGIBLE"
    audit_card = card("Official-price audit", f'''<p><strong>{audit_state}</strong>
for the official Nasdaq backend. The current run backend is
<code>{ESC(d.price_backend)}</code> with class
<code>{ESC(", ".join(d.price_classes) or "UNKNOWN")}</code>.</p>
<p>Required checks include the raw response checksum, collection-manifest match,
retrieval timestamp, ISO date coverage for every FRED session, OHLCV invariants,
dividend status and explicit redistribution status. Run
<code>python3 -m sim.cli price-audit</code> for the complete report.</p>''', cls="notice")
    body = f"""
<h1>Data custody &mdash; where every price came from</h1>
<p class="lede">Season 2's inputs are committed to the repository exactly as they
arrived, and every one of them is recorded in the collection manifest with its URL,
HTTP status, byte count and SHA-256. {len(ok):,} requests succeeded and
{len(failed):,} failed in the collection run that fed this season; the failures are
listed too, because a source that could not be retrieved is part of the record.
The official-price audit below is a separate gate: retrieval, source identity and
redistribution permission must all pass.</p>
{audit_card}
{_kpis([
    ("Collected files", f"{inventory.get('file_count', 0):,}",
     f"{inventory.get('bytes', 0) / 1e6:,.1f} MB under data/real/"),
    ("Price series", str(len(diag.get("price_series") or {})),
     "collected daily bars, 24 of them traded"),
    ("Sessions", f"{diag.get('sessions', {}).get('competition', 0)} competition + "
                 f"{diag.get('sessions', {}).get('warmup', 0)} warm-up",
     "the real US equity calendar, from FRED's observation dates"),
    ("Forward-filled sessions", str(diag.get("sessions_forward_filled_total", 0)),
     "a missing print is flagged, never interpolated"),
    ("SPY vs FRED S&P 500 return correlation", str(cross.get("return_correlation", "—")),
     f"worst daily difference {cross.get('max_abs_daily_return_diff', '—')}"),
])}
{card("What is collected, what is modelled", '''
<h3>Collected observations and source classes</h3>
<ul>
<li><strong>Prices and volumes</strong> for every traded symbol: the current
committed research run reads collected vendor daily bars under
<code>data/real/prices/yahoo/</code>, each file hashed and listed below. Yahoo is an
aggregator, so its class is SECONDARY. The official Nasdaq adapter writes separate
normalized files plus raw responses under <code>data/real/</code>, but the strict gate
also requires explicit redistribution permission.</li>
<li><strong>The market and volatility path</strong>: FRED <code>SP500</code> and
<code>VIXCLS</code> daily closes, i.e. the official reserve-bank series.</li>
<li><strong>The calendar</strong>: FRED's observation dates, so holidays are the
observed exchange dates rather than a hand-typed list.</li>
<li><strong>The events</strong>: SEC EDGAR Form 4 filings, openFDA decisions, the
official MLB schedule feed, NOAA/NCEI daily summaries, FRED yields and the Kalshi
settled-market list, each with the endpoint recorded.</li>
</ul>
<h3>Modelled (declared, and stress-tested)</h3>
<ul>
<li>The intraday path inside each collected daily bar: the open/high/low/close and
volume are observed fields, but the sequence of prices between them is not
observable from daily data.</li>
<li>The venue: quoted spread, displayed depth, impact, participation cap, borrow fees
and market-maker behaviour, all as declared in <code>sim/config.py</code> and
registered as IR-40 to IR-46.</li>
<li>Dividend treatment is only applied when the selected source records an event;
the current Yahoo research run uses a secondary event feed, while the official
adapter records a separate dividend endpoint and refuses incomplete status in the
strict audit.</li>
</ul>
<h3>Not retrieved</h3>
<ul>
<li>Consolidated-tape intraday history, which would be the only way to make the
intraday path observed. No free, redistributable tape exists.</li>
<li>An archived NFL/NBA injury series and pre-game model snapshots: those documents
are published live, so the strategies that read them run forward-only.</li>
</ul>''', cls="notice")}
{card("Collected price series", table(
    ["symbol", "provider", "class", "collected bars", "sessions", "forward-filled",
     "dividends", "beta vs FRED SPX (warm-up)", "idiosyncratic vol", "sha256",
     "file"], price_rows))}
{card("Requests recorded by the collector", table(
    ["kind", "result", "http", "bytes", "url", "error"], req_rows))}
{card("Every file the season depends on", table(
    ["path", "bytes", "sha256"], inv_rows))}
"""
    return page("Data custody", body, active="season2/data.html")


def build_participants_index(d: Season2Site) -> str:
    rows = []
    for r in d.leaderboard:
        user = r["username"]
        rep = d.reports.get(user, {})
        spec = d.spec(user)
        narrative = rep.get("narrative") or {}
        rows.append([
            f'<a href="{_slug(user)}.html">{ESC(user)}</a>',
            ESC(str(spec.get("display_name", ""))),
            ESC(str(r.get("archetype", ""))),
            signed(r["total_return_pct"]),
            money(r.get("final_equity")),
            signed(r.get("max_drawdown_pct")),
            num(rep.get("sessions_with_orders"), F0),
            badge(str(narrative.get("verdict", ""))),
            ESC(str(spec.get("thesis", ""))[:180]),
        ])
    body = f"""
<h1>Season 2 participants</h1>
<p class="lede">One page per username: the strategy as declared before the run, the
result, a post-mortem built only from measured quantities, the round trips with their
collected reference prices, and the verification block that says whether the account
re-derives from the raw fills.</p>
{table(["username", "strategy", "archetype", "total return %", "final equity",
        "max DD %", "sessions with orders", "verdict", "thesis"], rows)}
"""
    return page("Participants", body, active="season2/participants/index.html", depth=2)


def build_participant(d: Season2Site, username: str) -> str:
    rep = d.reports.get(username)
    spec = d.spec(username)
    ver = d.verification_for(username)
    if not rep:
        return page(username, f"<h1>{ESC(username)}</h1><p>No report in this run.</p>",
                    depth=1)
    curve = d.curve(username)
    charts = []
    if curve:
        charts.append(line_chart([(username, curve), ("S&P 500 scaled", d.benchmark())],
                                 title="Equity against the real S&P 500",
                                 y_format=FD0))
        peak, dd = -1e18, []
        for date, eq in curve:
            peak = max(peak, eq)
            dd.append((date, 100.0 * (eq / peak - 1.0) if peak else 0.0))
        charts.append(line_chart([("Drawdown", dd)], height=200, y_format="{:+.0f}%",
                                 title="Drawdown from the running peak", baseline=0))
    monthly = [(str(m.get("month", ""))[2:], m.get("return_pct", 0.0))
               for m in (rep.get("monthly_returns") or [])]
    if monthly:
        charts.append(bar_chart(monthly, height=240, y_format=FC0SP,
                                title="Monthly return (%)"))
    contrib = rep.get("contribution_by_symbol") or []
    if contrib:
        charts.append(hbar_chart([(c["symbol"], c.get("total_pnl", 0.0))
                                  for c in contrib],
                                 title="P&L contribution by instrument (USD)"))
    narrative = rep.get("narrative") or {}
    prose = narrative.get("prose") or []
    narrative_html = "".join(
        f'<section class="prose-block"><h3>{ESC(str(p.get("title", "")))}</h3>'
        f'<p>{ESC(str(p.get("text", "")))}</p></section>' for p in prose)
    if not narrative_html:
        narrative_html = "<p class='muted'>No narrative was generated.</p>"
    else:
        narrative_html = (
            f'<p class="muted small">{ESC(str(narrative.get("headline", "")))}</p>'
            + narrative_html)
    signals = {k: v for k, v in (d.masterfeed.get("fire_counts") or {}).items()
               if k in set(spec.get("signal_names") or [])}
    signal_rows = [[f"<code>{ESC(k)}</code>", pill(str(v.get("state", ""))),
                    str(v.get("sessions_actionable", "—")),
                    str(v.get("sessions_in_window", "—")),
                    num(v.get("last_value"), F4)]
                   for k, v in sorted(signals.items())]
    trips = sorted([t for t in d.trips_for(username) if t.get("status") == "closed"],
                   key=lambda t: -abs(t.get("net_pnl_usd", 0.0)))[:40]
    trip_rows = [[ESC(str(t.get("symbol"))), ESC(str(t.get("direction"))),
                  ESC(str(t.get("entry_date"))), f'{t.get("entry_price", 0):.2f}',
                  ESC(str(t.get("exit_date"))), f'{t.get("exit_price", 0):.2f}',
                  str(t.get("quantity", "")), money(t.get("gross_pnl_usd")),
                  money(t.get("fees_usd")), money(t.get("net_pnl_usd")),
                  num(t.get("entry_reference_close"), FC2),
                  num(t.get("exit_reference_close"), FC2),
                  ESC(str(t.get("exit_reason") or t.get("entry_reason") or "")[:60])]
                 for t in trips]
    fills = sorted(d.fills_for(username),
                   key=lambda f: (f.get("date", ""), f.get("symbol", "")))[:40]
    fill_rows = [[ESC(str(f.get("date"))), ESC(str(f.get("symbol"))),
                  ESC(str(f.get("side"))), str(f.get("filled_qty")),
                  f'{f.get("avg_price", 0):.4f}', num(f.get("reference_close"), FC2),
                  num(f.get("participation_pct_of_session_volume"), F5),
                  num(f.get("slippage_vs_open_bps"), F2),
                  num(f.get("slippage_vs_close_bps"), F2),
                  num(f.get("total_cost"), F4),
                  f'<code>{ESC(str(f.get("reference_file", "")))}</code>']
                 for f in fills]
    errors = rep.get("errors") or []
    body = f"""
<h1>{ESC(username)} <span class="muted">{ESC(str(spec.get('display_name', '')))}</span></h1>
<p class="lede">{ESC(str(spec.get('thesis', '')))}</p>
{_kpis([
    ("Total return", signed(rep.get("total_return_pct")), "rank metric"),
    ("Final equity", money(rep.get("final_equity")), "$100,000 starting capital"),
    ("Max drawdown", signed((rep.get("risk") or {}).get("max_drawdown_pct")),
     "peak to trough on the equity curve"),
    ("Sharpe", num((rep.get("risk") or {}).get("sharpe"), F2),
     "daily returns, annualised"),
    ("Beta to the real S&amp;P 500", num((rep.get("market_relation") or {}).get("beta"), F2),
     "the real FRED index, not a proxy"),
    ("Realised P&L (re-derived)", money(ver.get("derived_realized_pnl_usd")),
     "from the raw fill stream by sim/ledger.py"),
    ("Equity residual", num(ver.get("equity_residual_usd"), F4),
     f'within a rounding bound of {money(ver.get("rounding_bound_usd"))}'),
    ("Signal-dependent", "yes" if ver.get("signal_dependent") else "no",
     "a strategy whose trades need a collected signal file"),
])}
{_grid(charts)}
{card("Why it returned what it returned", narrative_html)}
{card("The strategy as declared before the run", f'''
<p><strong>Entry rules</strong></p>
<ul>{''.join(f'<li>{ESC(str(x))}</li>' for x in (spec.get('entry_rules') or []))}</ul>
<p><strong>Exit rules</strong></p>
<ul>{''.join(f'<li>{ESC(str(x))}</li>' for x in (spec.get('exit_rules') or []))}</ul>
<p><strong>Sizing:</strong> {ESC(str(spec.get('sizing', '')))} &middot;
<strong>Leverage:</strong> {ESC(str(spec.get('leverage', '')))} &middot;
<strong>Cadence:</strong> {ESC(str(spec.get('cadence', '')))} &middot;
<strong>Horizon:</strong> {ESC(str(spec.get('horizon', '')))}</p>
<p><strong>Declared failure modes</strong></p>
<ul>{''.join(f'<li>{ESC(str(x))}</li>' for x in (spec.get('known_failure_modes') or []))}</ul>''')}
{card("Signals this participant reads", table(
    ["signal", "collected state", "sessions actionable", "sessions in window",
     "value on the last session"], signal_rows)
    if signal_rows else "<p class='muted'>This participant reads collected prices directly "
                       "(technical rules); it does not depend on a collected event "
                       "signal.</p>")}
{card("Round trips (largest 40)", table(
    ["symbol", "direction", "entry", "entry px", "exit", "exit px", "qty", "gross $",
     "fees $", "net $", "collected close on entry", "collected close on exit", "reason"],
    trip_rows) if trip_rows else
    "<p class='muted'>No closed round trips: the signal had no collected history this "
    "season, so the strategy correctly placed no backdated trades.</p>")}
{card("First 40 fills against the collected bar", table(
    ["date", "symbol", "side", "qty", "fill px", "collected close", "participation %",
     "slip vs open (bps)", "slip vs close (bps)", "modelled cost $", "price file"],
    fill_rows) if fill_rows else "<p class='muted'>No fills.</p>")}
{card("Verification", f'''
<ul>
<li>Equity re-derived from the raw fills: {money(ver.get('derived_final_equity_usd'))}
against the engine's {money(ver.get('engine_final_equity_usd'))} &mdash; residual
{num(ver.get('equity_residual_usd'), F4)} USD, within the rounding bound of
{money(ver.get('rounding_bound_usd'))} that 6-decimal stored prices can produce.</li>
<li>Realised P&amp;L: engine {money(ver.get('engine_realized_pnl_usd'))} (net of
explicit fees) against the re-derived {money(ver.get('derived_realized_pnl_usd'))}
(also net of fees).</li>
<li>Open positions at the season end: {ESC(json.dumps(ver.get('open_positions', {}))[:200])}
&mdash; the competition force-liquidates everything on the last session, so this must
be empty.</li>
<li>Errors raised during the run: {ESC(json.dumps(errors)[:200]) if errors else 'none'}.</li>
</ul>''')}
<p><a href="../ledger.html">Trade ledger</a> &middot;
<a href="index.html">All participants</a> &middot;
<a href="../masterfeed.html">MasterFeed register</a></p>
"""
    return page(username, body, active="season2/participants/index.html", depth=2)


def _mean(values: Iterable[Optional[float]]) -> Optional[float]:
    vals = [v for v in values if v is not None]
    return round(sum(vals) / len(vals), 5) if vals else None


# --------------------------------------------------------------------------

#: Marker for the Season 2 links injected into Season 1's pages. Its presence is
#: what makes ``inject_banner`` idempotent: a page that already carries the
#: banner is returned unchanged, so the injection can be applied to a whole
#: directory without tracking which files were already done.
BANNER_MARK = 'id="season2-banner"'

BANNER_CALLOUT = (
    '<section id="season2-banner" class="card">'
    '<h2>Season 2 is published with an explicit price-eligibility status</h2>'
    '<p>Season 1 above is a calibrated replay of the real S&amp;P 500 and VIX path. '
    '<strong>Season 2</strong> preserves every collected price file, raw response, '
    'checksum and trade-ledger fact, but a public endpoint is not automatically an '
    'eligible official source. The current Yahoo-backed history is marked '
    '<strong>SECONDARY research</strong>; the official Nasdaq path fails closed until '
    'source, coverage, checksum and redistribution checks pass.</p>'
    '<p><a href="{p}season2/index.html">Season 2 overview</a> · '
    '<a href="{p}season2/leaderboard.html">Leaderboard</a> · '
    '<a href="{p}season2/ledger.html">Verified trade ledger</a> · '
    '<a href="{p}season2/masterfeed.html">MasterFeed register</a> · '
    '<a href="{p}season2/data.html">Data custody</a></p>'
    '</section>')


def inject_banner(html_text: str, callout: bool = True, prefix: str = "") -> str:
    """Add the Season 2 links to a Season 1 page, once.

    Two edits, both idempotent: a nav entry appended to the site's own ``<nav>``
    (every page, so the Season 2 section is reachable from anywhere) and, on the
    overview page only, a callout that says what Season 2 is.  The nav is found by
    its ``</nav>`` close rather than by rewriting the nav list, because Season 1's
    page shell is built by a different script and must stay the single owner of
    its own markup.
    """
    if BANNER_MARK in html_text:
        return html_text
    nav_link = f'<a href="{prefix}season2/index.html">Season 2 (eligibility status)</a>'
    if '</nav>' in html_text:
        html_text = html_text.replace('</nav>', nav_link + '</nav>', 1)
    if callout:
        marker = '<main class="wrap">'
        if marker in html_text:
            html_text = html_text.replace(
                marker, marker + "\n" + BANNER_CALLOUT.format(p=prefix), 1)
        else:  # pragma: no cover - the shell always has a <main>
            html_text = BANNER_CALLOUT.format(p=prefix) + html_text
    return html_text


def _price_status_banner(d: Season2Site) -> str:
    audit = d.price_eligibility
    run_eligible = (audit.get("eligible") and d.price_backend == "nasdaq" and
                    d.price_classes and set(d.price_classes) == {"OFFICIAL"})
    if run_eligible:
        return (
            '<section class="card notice" style="border-color:#1f9d55">'
            '<h2>Official-price eligibility: PASS</h2>'
            '<p>All required symbols passed source-class, raw-response checksum, '
            'retrieval, OHLCV, session-coverage and redistribution checks for the '
            f'{ESC(str(audit.get("backend")))} backend.</p></section>')
    codes = sorted({str(issue.get("code", "invalid")) for issue in audit.get("issues", [])})
    return (
        '<section class="card notice" style="border-color:#c0392b">'
        '<h2>Official-price eligibility: NOT ELIGIBLE</h2>'
        f'<p>This committed run uses <strong>{ESC(d.price_backend)}</strong> price files '
        f'classed <strong>{ESC(", ".join(d.price_classes) or "UNKNOWN")}</strong>. '
        'It is reproducible research, not an official-price competition result. '
        'The strict runner uses the Nasdaq adapter and refuses to trade when official '
        'files, raw checksums, complete dates, OHLCV validation or redistribution '
        'permission are missing.</p>'
        f'<p><strong>Audit flags:</strong> {ESC(", ".join(codes[:12]) or "none")}. '
        'Run <code>python3 -m sim.cli price-audit</code> for the complete report; '
        'no Yahoo/Nasdaq agreement can override this gate.</p></section>')


def build(root: str, out: str, run_id: str = "") -> List[str]:
    global PRICE_STATUS_BANNER
    d = Season2Site(root, run_id)
    PRICE_STATUS_BANNER = _price_status_banner(d)
    written: List[str] = []

    def write(rel: str, content: str) -> None:
        path = os.path.join(out, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)
        written.append(rel)

    write("season2/index.html", build_index(d))
    write("season2/leaderboard.html", build_leaderboard(d))
    write("season2/masterfeed.html", build_masterfeed(d))
    write("season2/ledger.html", build_ledger(d))
    write("season2/stress.html", build_stress(d))
    write("season2/data.html", build_data(d))
    write("season2/participants/index.html", build_participants_index(d))
    for username in sorted(d.reports):
        write(f"season2/participants/{_slug(username)}.html",
              build_participant(d, username))

    payloads = {
        "leaderboard.json": d.leaderboard,
        "participants.json": d.participants,
        "masterfeed.json": d.masterfeed,
        "stress_panel.json": d.stress,
        "ledger_summary.json": {
            "summary": d.verification.get("summary"),
            "digest_sha256": d.verification.get("ledger_digest_sha256"),
            "verification": d.verification.get("per_participant"),
        },
        "crosschecks.json": (d.verification.get("summary") and
                             (d.verification or {}).get("summary")) or {},
        "market_summary.json": d.market,
        "price_eligibility.json": d.price_eligibility,
    }
    for name, payload in payloads.items():
        write(f"assets/data/season2/{name}",
              json.dumps(payload, indent=1, sort_keys=False) + "\n")

    # Prune anything this builder no longer produces. ``docs/`` is committed and
    # diffed against a fresh build in CI, and a JSON payload from an earlier
    # revision of this script (``collected_data.json`` was observed) would keep
    # being served - and keep being diffed - as if it were current. Season 1's
    # builder prunes its participant pages for the same reason.
    keep = set(written)
    for base in ("season2", os.path.join("assets", "data", "season2")):
        directory = os.path.join(out, base)
        if not os.path.isdir(directory):
            continue
        for name in sorted(os.listdir(directory)):
            rel = os.path.join(base, name)
            path = os.path.join(directory, name)
            if os.path.isdir(path):
                continue
            if rel not in keep:
                os.remove(path)
    return written


def main(argv: Optional[Sequence[str]] = None) -> int:
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--memory-root", default=os.path.join(REPO_ROOT, "memory"))
    parser.add_argument("--out", default=os.path.join(REPO_ROOT, "docs"))
    parser.add_argument("--run", default="")
    args = parser.parse_args(argv)
    written = build(args.memory_root, args.out, args.run)
    print(f"season 2 site: {len(written)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
